#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./run-parallel

restore0Dir

runApplication decomposePar -force

runApplication mpirun --oversubscribe -np 12 XiFoam -parallel

runApplication reconstructPar

#------------------------------------------------------------------------------
